#!/usr/bin/env python3
"""Assemble rendered frames into a VCMI mod, ready for the validator.

    assemble_mod.py --frames render/skeleton --mod ~/vcmi-mods/hd-creatures \\
                    --creature CSKELE --lod "$LOD"

render_sprites.py already names frames the way the animation JSON expects
(`holding_00.png`, `attack_front_03-shadow.png`), so this copies them into the
mod's basepath and writes an animation JSON covering only the groups that were
actually rendered — a partial replacement is fine, the engine falls back to the
original `.def` for anything missing.

With --lod, group ids and the canvas come from the original rather than from a
table here, so a creature nobody has thought about yet still assembles correctly.
"""

import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from vcmi_anim import GROUP_IDS, GROUP_NAMES, SCALE_DIRS  # noqa: E402

FRAME = re.compile(r"^(?P<group>[a-z_]+)_(?P<index>\d+)(?P<layer>-shadow|-overlay)?\.png$")


def scan(frames_dir):
    """{group name: {index: {layer: path}}} from the rendered filenames."""
    found = {}
    for path in sorted(Path(frames_dir).iterdir()):
        match = FRAME.match(path.name)
        if not match:
            continue
        group = match.group("group").upper()
        if group not in GROUP_IDS:
            continue
        index = int(match.group("index"))
        layer = (match.group("layer") or "")[1:] or "body"
        found.setdefault(group, {}).setdefault(index, {})[layer] = path
    return found


def main(argv=None):
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--frames", required=True, help="directory of rendered frames")
    parser.add_argument("--mod", type=Path, required=True)
    parser.add_argument("--creature", required=True, help="animation name, e.g. CSKELE")
    parser.add_argument("--scale", type=int, default=1, choices=sorted(SCALE_DIRS))
    parser.add_argument("--name", default="HD Creatures")
    args = parser.parse_args(argv)

    creature = args.creature.upper()
    groups = scan(args.frames)
    if not groups:
        raise SystemExit("no frames matching <group>_NN[-layer].png in %s" % args.frames)

    basepath = "creatures/%s/" % creature.lower()
    sprites = args.mod / "content" / SCALE_DIRS[args.scale]
    target = sprites / basepath
    target.mkdir(parents=True, exist_ok=True)

    mod_json = args.mod / "mod.json"
    if not mod_json.exists():
        mod_json.parent.mkdir(parents=True, exist_ok=True)
        mod_json.write_text(json.dumps({
            "name": args.name,
            "description": "Replacement creature artwork",
            "version": "0.1",
            "author": "",
            "contact": "",
            "modType": "Graphical",
        }, indent=4) + "\n")

    sequences, copied, missing = [], 0, []
    for group in sorted(groups, key=lambda g: GROUP_IDS[g]):
        indices = sorted(groups[group])
        if indices != list(range(len(indices))):
            raise SystemExit("%s has gaps in its frame numbering: %s" % (group, indices))

        names = []
        for index in indices:
            layers = groups[group][index]
            if "body" not in layers:
                raise SystemExit("%s frame %d has no body layer" % (group, index))
            for layer, path in sorted(layers.items()):
                shutil.copy2(path, target / path.name)
                copied += 1
            for needed in ("shadow", "overlay"):
                if needed not in layers:
                    missing.append("%s_%02d-%s" % (group.lower(), index, needed))
            names.append(layers["body"].name)

        sequences.append({"group": GROUP_IDS[group], "frames": names})

    animation = sprites / ("%s.json" % creature)
    animation.write_text(
        "// %s -- generated by assemble_mod.py\n" % creature
        + "// Groups not listed here fall back to the original .def.\n"
        + json.dumps({"basepath": basepath, "sequences": sequences}, indent=4) + "\n")

    print("%s: %d group(s), %d frame(s), %d file(s) copied"
          % (creature, len(sequences), sum(len(groups[g]) for g in groups), copied))
    for entry in sequences:
        print("  %-3d %-18s %d frames" % (entry["group"], GROUP_NAMES[entry["group"]], len(entry["frames"])))
    if missing:
        print("\nwarning: %d frame(s) have no shadow or overlay layer" % len(missing))
        print("  first: %s" % ", ".join(missing[:4]))
    print("\nvalidate with:")
    print("  validate_creature_animation.py %s" % args.mod)
    return 0


if __name__ == "__main__":
    sys.exit(main())
